import './check.mjs';
import {mkdir,copyFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const files=['index.html','styles.css','script.js','assets/huayang-vista-logo.svg','assets/consult-qr.jpg'];
await mkdir(path.join(root,'dist/assets'),{recursive:true});
for(const file of files) await copyFile(path.join(root,file),path.join(root,'dist',file));
await writeFile(path.join(root,'dist/.nojekyll'),'');
console.log('Build complete: dist/ (static site, no runtime dependencies).');
